export const pets = [
    {
        id: 1,
        name: 'Shiwawa',
        location: 'Nigeria',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 2,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 3,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 4,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 5,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 6,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 7,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 8,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 9,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 10,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 11,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
    {
        id: 12,
        name: 'Pows Shelters',
        location: 'South Carolina',
        image: '_placeholderImage.png',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Max',

    },
]

export const breeder = [
    {
        id: 1,
        name: 'Pawis',
        location: 'Nigeria',
        image: 'breeder.jpg',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Charlotte',

    },
    {
        id: 2,
        name: 'All dogs',
        location: 'South Carolina',
        image: 'ricky.jpg',
        breed: 'Large breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Ricky',

    },
    {
        id: 3,
        name: 'Awesome pets',
        location: 'South Carolina',
        image: 'breeder.jpg',
        breed: 'Mixed breed',
        age: '2 years',
        gender: 'Male',
        description: 'This impressive paella is a perfect party dish and a fun meal to cook together.',
        breeder: 'Pamela',

    },
]
