name: Deploy To Development
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: yarn install --frozen-lockfile

        - name: Build
          run: GENERATE_SOURCEMAP=false CI=false REACT_APP_ENVIRONMENT=dev yarn build

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: www.yourpats.com
            bucket-region: us-east-1
            delete-removed: true
            no-cache: true
            private: false
